      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript - <<'RS'
          repos <- "https://cloud.r-project.org"
          if (!requireNamespace("rsconnect", quietly = TRUE))
            install.packages(c("curl","openssl","jsonlite","snowflakeauth","rsconnect"), repos = repos)

          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_NAME"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )

          # Déployer le dossier courant ; grâce à .rsconnectignore,
          # renv.lock, renv/ et .github/ seront exclus du bundle.
          rsconnect::deployApp(
            appDir      = ".",
            appName     = "FeuxSaguenay2023",
            forceUpdate = TRUE,
            logLevel    = "normal"
          )
          RS
