name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - "app.R"
      - "data/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: shinyapps-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to shinyapps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          # -------------------------------
          # Nom de l'app sur shinyapps.io :
          # https://<account>.shinyapps.io/<appName>
          # -------------------------------
          appName: FeuxSaguenay2023
          accountName: ${{ secrets.SHINYAPPS_NAME }}
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}

          # Racine du repo (laisse "/" si app.R est à la racine)
          appDir: "/"

          # Pour n’envoyer que l’essentiel au bundle
          appFiles: "app.R,data"

          # (Optionnel) titre lisible côté shinyapps
          appTitle: "Feux 2023 — Saguenay–Lac-Saint-Jean"

          # (Optionnel) verbosité rsconnect
          logLevel: "normal"
