name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - app.R
      - data/**
      - DESCRIPTION
      - .rsconnectignore
      - .github/workflows/deploy.yml
  workflow_dispatch:

concurrency:
  group: shinyapps-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install system libraries for rsconnect/curl
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev libssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Optionnel mais utile si un ancien id rsconnect traîne dans le repo
      - name: Clear stale rsconnect record (optional)
        run: rm -rf rsconnect

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript - <<'RS'
          repos <- "https://cloud.r-project.org"
          # Installer rsconnect et deps minimales (sur le runner GitHub uniquement)
          pkgs <- c("curl","openssl","jsonlite","snowflakeauth","rsconnect")
          for (p in pkgs) if (!requireNamespace(p, quietly = TRUE))
            install.packages(p, repos = repos)

          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_NAME"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )

          deploy <- function() {
            rsconnect::deployApp(
              appDir      = ".",
              appName     = "FeuxSaguenay2023",
              forceUpdate = TRUE,
              logLevel    = "normal"
            )
          }

          # Si l’app a été supprimée/ recréée côté shinyapps, on oublie l’ancien enregistrement et on réessaie
          tryCatch(
            deploy(),
            error = function(e) {
              msg <- conditionMessage(e)
              if (grepl("applicationDeleted", msg, fixed = TRUE) ||
                  grepl("Failed to find existing application on server", msg)) {
                message("Stale deployment record detected. Forgetting and retrying...")
                suppressWarnings(
                  rsconnect::forgetDeployment(
                    appName = "FeuxSaguenay2023",
                    account = Sys.getenv("SHINYAPPS_NAME"),
                    server  = "shinyapps.io"
                  )
                )
                deploy()
              } else {
                stop(e)
              }
            }
          )
          RS
