name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - "app.R"
      - "data/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: shinyapps-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to shinyapps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Deploy
        uses: BDSI-Utwente/shinyapps-deploy-github-action@v1
        with:
          appName: FeuxSaguenay2023
          accountName: ${{ secrets.SHINYAPPS_NAME }}
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
          appDir: "/"
          # <-- ajoute renv.lock et renv/activate.R
          appFiles: "app.R,data,renv.lock,renv/activate.R,.Rprofile"
          appTitle: "LES FEUX DE FORÊT AU SAGUENAY–LAC-SAINT-JEAN DE 2023"
          logLevel: "normal"

