name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
    paths:
      - "app.R"
      - "data/**"
      - "renv.lock"
      - "renv/activate.R"
      - ".Rprofile"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: shinyapps-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # ⬇️ On installe et on déploie dans le MÊME Rscript (plus aucun "no package rsconnect")
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME:   ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN:  ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript - <<'RS'
          repos <- "https://cloud.r-project.org"
          if (!requireNamespace("rsconnect", quietly = TRUE))
            install.packages("rsconnect", repos = repos)

          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_NAME"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )

          rsconnect::deployApp(
            appName  = "FeuxSaguenay2023",
            appFiles = c("app.R","data","renv.lock","renv/activate.R",".Rprofile"),
            logLevel = "normal"
          )
          RS
